version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: ${GATEWAY_ROUTE_0_ID}
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: ${GATEWAY_ROUTE_0_URI}
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: ${GATEWAY_ROUTE_0_PREDICATES_0}

      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: ${GATEWAY_ROUTE_1_ID}
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: ${GATEWAY_ROUTE_1_URI}
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: ${GATEWAY_ROUTE_1_PREDICATES_0}

      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: ${GATEWAY_ROUTE_2_ID}
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: ${GATEWAY_ROUTE_2_URI}
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: ${GATEWAY_ROUTE_2_PREDICATES_0}

    networks:
      - payment-system-network

networks:
  payment-system-network:
    external: true
    name: payment-system-network