spring.application.name=gateway

server.port=${SERVER_PORT:8084}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/payment-system}

spring.cloud.gateway.routes[0].id=${GATEWAY_ROUTE_0_ID:authentication-service}
spring.cloud.gateway.routes[0].uri=${GATEWAY_ROUTE_0_URI:http://localhost:8085}
spring.cloud.gateway.routes[0].predicates[0]=${GATEWAY_ROUTE_0_PREDICATES_0:Path=/api/auth/**}

spring.cloud.gateway.routes[1].id=${GATEWAY_ROUTE_1_ID:user-service}
spring.cloud.gateway.routes[1].uri=${GATEWAY_ROUTE_1_URI:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=${GATEWAY_ROUTE_1_PREDICATES_0:Path=/api/users/**}

spring.cloud.gateway.routes[2].id=${GATEWAY_ROUTE_2_ID:order-service}
spring.cloud.gateway.routes[2].uri=${GATEWAY_ROUTE_2_URI:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=${GATEWAY_ROUTE_2_PREDICATES_0:Path=/api/v1/orders/**}

management.endpoints.web.exposure.include=health,info